import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import Favicon from "./favicon.png";
import { ReduxProvider } from './ReduxProvider';
import { Toaster } from 'react-hot-toast';

const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NoteNest',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: Favicon.src }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ReduxProvider>
          {children}
          <Toaster position="top-center" reverseOrder={false} />
        </ReduxProvider>
      </body>
    </html>
  )
}